server {
    include snippets/deny-bakfiles.conf;
    listen 443 ssl;  # TLS terminé ici, en direct
    server_name farm.example.org;
    ssl_certificate     /etc/ssl/farm.example.org/fullchain.pem;
    ssl_certificate_key /etc/ssl/farm.example.org/privkey.pem;

    include snippets/security-headers-base.conf;
    include snippets/hsts.conf;
    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_http_version 1.1;
    }
}
